// Package imdb fetches IMDb's own free, official non-commercial ratings
// dataset (title.ratings.tsv.gz at datasets.imdbws.com) — updated daily,
// no API key, no rate limit, unlike a metered API (e.g. OMDb) wrapping the
// same underlying data. It contains a rating and vote count for every
// title IMDb tracks, keyed by IMDb id (tconst) — the same id Radarr and
// Sonarr already report for every movie/series (Media.IMDBID), so this
// covers both uniformly even though Sonarr's own API has no per-source
// rating split the way Radarr's does.
package imdb

import (
	"bufio"
	"compress/gzip"
	"context"
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"time"
)

const defaultDatasetURL = "https://datasets.imdbws.com/title.ratings.tsv.gz"

// Rating is one title's IMDb rating/vote-count pair.
type Rating struct {
	Tconst string
	Value  float64
	Votes  int
}

type Client struct {
	datasetURL string
	hc         *http.Client
}

func New() *Client {
	return &Client{datasetURL: defaultDatasetURL, hc: &http.Client{Timeout: 5 * time.Minute}}
}

// NewWithDatasetURL is New with the dataset location overridden — for
// tests that need a local httptest fixture instead of the real dataset.
func NewWithDatasetURL(datasetURL string) *Client {
	return &Client{datasetURL: datasetURL, hc: &http.Client{Timeout: 5 * time.Minute}}
}

// FetchRatings downloads and parses the full dataset. A malformed
// individual row (short, non-numeric fields) is skipped rather than
// failing the whole fetch — the file is generated by IMDb itself and
// essentially always well-formed, but a bad line shouldn't discard every
// other title's real data.
func (client *Client) FetchRatings(ctx context.Context) ([]Rating, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, client.datasetURL, nil)
	if err != nil {
		return nil, err
	}
	resp, err := client.hc.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode/100 != 2 {
		return nil, fmt.Errorf("imdb dataset %s: %s", client.datasetURL, resp.Status)
	}
	gz, err := gzip.NewReader(resp.Body)
	if err != nil {
		return nil, err
	}
	defer gz.Close()

	scanner := bufio.NewScanner(gz)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	out := make([]Rating, 0, 1_500_000)
	first := true
	for scanner.Scan() {
		if first {
			// Header row: tconst\taverageRating\tnumVotes.
			first = false
			continue
		}
		fields := strings.Split(scanner.Text(), "\t")
		if len(fields) != 3 {
			continue
		}
		value, err := strconv.ParseFloat(fields[1], 64)
		if err != nil {
			continue
		}
		votes, err := strconv.Atoi(fields[2])
		if err != nil {
			continue
		}
		out = append(out, Rating{Tconst: strings.TrimSpace(fields[0]), Value: value, Votes: votes})
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	return out, nil
}
