package store

/*
#cgo LDFLAGS: -lsqlite3
#include <sqlite3.h>
#include <stdlib.h>
*/
import "C"

import "time"

// CreateSession persists a new login session token. token is expected to
// already be a cryptographically random, unguessable value generated by the
// caller — the store only ever compares tokens for exact equality, never
// derives or validates their entropy.
func (s *Store) CreateSession(token string, expiresAt time.Time) error {
	s.accessMu.Lock()
	defer s.accessMu.Unlock()
	st, err := s.prepare(`INSERT INTO sessions(token,created_at,expires_at) VALUES(?,?,?)`)
	if err != nil {
		return err
	}
	defer C.sqlite3_finalize(st)
	bindText(st, 1, token)
	bindText(st, 2, time.Now().UTC().Format(time.RFC3339Nano))
	bindText(st, 3, expiresAt.UTC().Format(time.RFC3339Nano))
	return stepDone(s, st)
}

// SessionValid reports whether token names a session that exists and has not
// yet expired. An expired session is lazily deleted here rather than left
// for a background sweep, since checking validity already required reading
// its row.
func (s *Store) SessionValid(token string) (bool, error) {
	s.accessMu.Lock()
	defer s.accessMu.Unlock()
	st, err := s.prepare(`SELECT expires_at FROM sessions WHERE token=?`)
	if err != nil {
		return false, err
	}
	defer C.sqlite3_finalize(st)
	bindText(st, 1, token)
	rc := C.sqlite3_step(st)
	if rc == C.SQLITE_DONE {
		return false, nil
	}
	if rc != C.SQLITE_ROW {
		return false, s.err(rc)
	}
	expiresAt, err := time.Parse(time.RFC3339Nano, colText(st, 0))
	if err != nil {
		return false, nil
	}
	if !time.Now().UTC().Before(expiresAt) {
		return false, s.deleteSession(token)
	}
	return true, nil
}

// DeleteSession removes one session, e.g. on logout.
func (s *Store) DeleteSession(token string) error {
	s.accessMu.Lock()
	defer s.accessMu.Unlock()
	return s.deleteSession(token)
}

func (s *Store) deleteSession(token string) error {
	st, err := s.prepare(`DELETE FROM sessions WHERE token=?`)
	if err != nil {
		return err
	}
	defer C.sqlite3_finalize(st)
	bindText(st, 1, token)
	return stepDone(s, st)
}

// DeleteAllSessions signs every session out at once — used after a password
// change so a credential rotation actually revokes access from any other
// still-logged-in browser instead of only the one that made the change.
func (s *Store) DeleteAllSessions() error {
	s.accessMu.Lock()
	defer s.accessMu.Unlock()
	return s.exec(`DELETE FROM sessions`)
}
